apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${{ values.app_name }}
  name: ${{ values.app_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.app_name }}
  template:
    metadata:
      labels:
        app: ${{ values.app_name }}
    spec:
      containers:
      - image: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/poc-rhdh-repository/${{ values.app_name }}:latest
        name: ${{ values.app_name }}
        ports:
        - containerPort: 3000
          protocol: TCP
      serviceAccountName: ${{ values.app_name }}-sa
